version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: dashboard:${BUILD_NUMBER}
    container_name: dashboard-${BRANCH_NAME}
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT=5432
      - DB_DATABASE
      - EMAIL_ADDRESS
      - EMAIL_PASSWORD
      - SECRET_OR_KEY
      - GOOGLE_CLIENT_ID
      - GOOGLE_SECRET
      - EMAIL_HOST
    restart: always
    ports:
      - "${PORT_NUMBER}:5000"
    volumes:
      - /opt/dashboard/logs-${BRANCH_NAME}:/usr/src/dashboard/logs:rw
      - /opt/dashboard/data-${BRANCH_NAME}:/usr/src/dashboard/public:rw
  db:
    image: postgres:11.2-alpine
    container_name: dashboard-postgres-${BRANCH_NAME}
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./dashboard/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
      - /opt/dashboard-db-${BRANCH_NAME}:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
