export const SET_ERRORS = 'SET_ERRORS'
export const SET_USER = 'SET_USER'
export const SET_MODAL = 'SET_MODAL'
export const SET_REGISTER_REDIRECT_RESPONSE = 'SET_REGISTER_REDIRECT_RESPONSE'
export const SET_RESPONSE_MESSAGE = 'SET_RESPONSE_MESSAGE'
export const SET_PAGE_ROUTE_PATH = 'SET_PAGE_ROUTE_PATH'
export const SET_TOAST_MESSAGE = 'SET_TOAST_MESSAGE'
export const SET_LOADING_SPINNER = 'SET_LOADING_SPINNER'
export const SET_PASSWORD_RESET_TOKEN = 'SET_PASSWORD_RESET_TOKEN'

export const SET_ISLOADING = 'SET_ISLOADING'
export const SET_UPLOAD_PERCENTAGE = 'SET_UPLOAD_PERCENTAGE'
export const SET_DRAWER = 'SET_DRAWER'


export const SET_SIDEBAR = 'SET_SIDEBAR'
